table_mapping = {
    1: "common",
    2: "uncommon_minor",
    3: "rare_minor",
    4: "very_rare_minor",
    5: "legendary_minor",
    6: "uncommon_major",
    7: "rare_major",
    8: "very_rare_major",
    9: "legendary_major",
    10: "mythic",
    11: "unknown"
}

resistance_types = [
    "Acid",
    "Cold",
    "Fire",
    "Force",
    "Lightning",
    "Necrotic",
    "Poison",
    "Psychic",
    "Radiant",
    "Thunder"
]

spells_by_level = {
    "Cantrip": [
        "Acid Splash (Conjuration)",
        "Chill Touch (Necromancy)",
        "Dancing Lights (Evocation)",
        "Druidcraft (Transmutation)",
        "Eldritch Blast (Evocation)",
        "Fire Bolt (Evocation)",
        "Guidance (Divination)",
        "Light (Evocation)",
        "Mage Hand (Conjuration)",
        "Mending (Transmutation)",
        "Message (Transmutation)",
        "Minor Illusion (Illusion)",
        "Poison Spray (Conjuration)",
        "Prestidigitation (Transmutation)",
        "Produce Flame (Conjuration)",
        "Ray of Frost (Evocation)",
        "Resistance (Abjuration)",
        "Sacred Flame (Evocation)",
        "Shillelagh (Transmutation)",
        "Shocking Grasp (Evocation)",
        "Spare the Dying (Necromancy)",
        "Thaumaturgy (Transmutation)",
        "True Strike (Divination)",
        "Vicious Mockery (Enchantment)"
    ],
    "1st Level": [
        "Alarm (Abjuration (Ritual))",
        "Animal Friendship (Enchantment)",
        "Bane (Enchantment)",
        "Bless (Enchantment)",
        "Burning Hands (Evocation)",
        "Charm Person (Enchantment)",
        "Color Spray (Illusion)",
        "Command (Enchantment)",
        "Comprehend Languages (Divination (Ritual))",
        "Create or Destroy Water (Transmutation)",
        "Cure Wounds (Evocation)",
        "Detect Evil and Good (Divination)",
        "Detect Magic (Divination (Ritual))",
        "Detect Poison and Disease (Divination (Ritual))",
        "Disguise Self (Illusion)",
        "Divine Favor (Evocation)",
        "Entangle (Conjuration)",
        "Expeditious Retreat (Transmutation)",
        "Faerie Fire (Evocation)",
        "False Life (Necromancy)",
        "Feather Fall (Transmutation)",
        "Find Familiar (Conjuration (Ritual))",
        "Floating Disk (Conjuration (Ritual))",
        "Fog Cloud (Conjuration)",
        "Goodberry (Transmutation)",
        "Grease (Conjuration)",
        "Guiding Bolt (Evocation)",
        "Healing Word (Evocation)",
        "Hellish Rebuke (Evocation)",
        "Heroism (Enchantment)",
        "Hideous Laughter (Enchantment)",
        "Hunter's Mark (Divination)",
        "Identify (Divination (Ritual))",
        "Illusory Script (Illusion (Ritual))",
        "Inflict Wounds (Necromancy)",
        "Jump (Transmutation)",
        "Longstrider (Transmutation)",
        "Mage Armor (Abjuration)",
        "Magic Missile (Evocation)",
        "Protection from Evil and Good (Abjuration)",
        "Purify Food and Drink (Transmutation (Ritual))",
        "Sanctuary (Abjuration)",
        "Shield (Abjuration)",
        "Shield of Faith (Abjuration)",
        "Silent Image (Illusion)",
        "Sleep (Enchantment)",
        "Speak with Animals (Divination (Ritual))",
        "Thunderwave (Evocation)",
        "Unseen Servant (Conjuration (Ritual))"
    ],
    "2nd Level": [
        "Acid Arrow",
        "Aid",
        "Alter Self",
        "Animal Messenger",
        "Arcane Lock",
        "Arcanist's Magic Aura",
        "Augury",
        "Barkskin",
        "Blindness/Deafness",
        "Blur",
        "Branding Smite",
        "Calm Emotions",
        "Continual Flame",
        "Darkness",
        "Darkvision",
        "Detect Thoughts",
        "Enhance Ability",
        "Enlarge/Reduce",
        "Enthrall",
        "Find Steed",
        "Find Traps",
        "Flame Blade",
        "Flaming Sphere",
        "Gentle Repose",
        "Gust of Wind",
        "Heat Metal",
        "Hold Person",
        "Invisibility",
        "Knock",
        "Lesser Restoration",
        "Levitate",
        "Locate Animals or Plants",
        "Locate Object",
        "Magic Mouth",
        "Magic Weapon",
        "Mirror Image",
        "Misty Step",
        "Moonbeam",
        "Pass without Trace",
        "Prayer of Healing",
        "Protection from Poison",
        "Ray of Enfeeblement",
        "Rope Trick",
        "Scorching Ray",
        "See Invisibility",
        "Shatter",
        "Silence",
        "Spider Climb",
        "Spike Growth",
        "Spiritual Weapon",
        "Suggestion",
        "Warding Bond",
        "Web",
        "Zone of Truth"
    ],
    "3rd Level": [
        "Animate Dead",
        "Beacon of Hope",
        "Bestow Curse",
        "Blink",
        "Call Lightning",
        "Clairvoyance",
        "Conjure Animals",
        "Counterspell",
        "Create Food and Water",
        "Daylight",
        "Dispel Magic",
        "Fear",
        "Fireball",
        "Fly",
        "Gaseous Form",
        "Glyph of Warding",
        "Haste",
        "Hypnotic Pattern",
        "Lightning Bolt",
        "Magic Circle",
        "Major Image",
        "Mass Healing Word",
        "Meld into Stone",
        "Nondetection",
        "Phantom Steed",
        "Plant Growth",
        "Protection from Energy",
        "Remove Curse",
        "Revivify",
        "Sending",
        "Sleet Storm",
        "Slow",
        "Speak with Dead",
        "Speak with Plants",
        "Spirit Guardians",
        "Stinking Cloud",
        "Tiny Hut",
        "Tongues",
        "Vampiric Touch",
        "Water Breathing",
        "Water Walk",
        "Wind Wall"
    ],
    "4th Level": [
        "Arcane Eye",
        "Banishment",
        "Black Tentacles",
        "Blight",
        "Compulsion",
        "Confusion",
        "Conjure Minor Elementals",
        "Conjure Woodland Beings",
        "Control Water",
        "Death Ward",
        "Dimension Door",
        "Divination",
        "Dominate Beast",
        "Fabricate",
        "Faithful Hound",
        "Fire Shield",
        "Freedom of Movement",
        "Giant Insect",
        "Greater Invisibility",
        "Guardian of Faith",
        "Hallucinatory Terrain",
        "Ice Storm",
        "Locate Creature",
        "Phantasmal Killer",
        "Polymorph",
        "Private Sanctum",
        "Resilient Sphere",
        "Secret Chest",
        "Stone Shape",
        "Stoneskin",
        "Wall of Fire"
    ],
    "5th Level": [
        "Animate Objects",
        "Antilife Shell",
        "Arcane Hand",
        "Awaken",
        "Cloudkill",
        "Commune",
        "Commune with Nature",
        "Cone of Cold",
        "Conjure Elemental",
        "Contact Other Plane",
        "Contagion",
        "Creation",
        "Dispel Evil and Good",
        "Dominate Person",
        "Dream",
        "Flame Strike",
        "Geas",
        "Greater Restoration",
        "Hallow",
        "Hold Monster",
        "Insect Plague",
        "Legend Lore",
        "Mass Cure Wounds",
        "Mislead",
        "Modify Memory",
        "Passwall",
        "Planar Binding",
        "Raise Dead",
        "Reincarnate",
        "Scrying",
        "Seeming",
        "Telekinesis",
        "Telepathic Bond",
        "Teleportation Circle",
        "Tree Stride",
        "Wall of Force",
        "Wall of Stone"
    ],
    "6th Level": [
        "Blade Barrier",
        "Chain Lightning",
        "Circle of Death",
        "Conjure Fey",
        "Contingency",
        "Create Undead",
        "Disintegrate",
        "Eyebite",
        "Find the Path",
        "Flesh to Stone",
        "Forbiddance",
        "Freezing Sphere",
        "Globe of Invulnerability",
        "Guards and Wards",
        "Harm",
        "Heal",
        "Heroes' Feast",
        "Instant Summons",
        "Irresistible Dance",
        "Magic Jar",
        "Mass Suggestion",
        "Move Earth",
        "Planar Ally",
        "Programmed Illusion",
        "Sunbeam",
        "Transport via Plants",
        "True Seeing",
        "Wall of Ice",
        "Wall of Thorns",
        "Wind Walk",
        "Word of Recall"
    ],
    "7th Level": [
        "Arcane Sword",
        "Conjure Celestial",
        "Delayed Blast Fireball",
        "Divine Word",
        "Etherealness",
        "Finger of Death",
        "Fire Storm",
        "Forcecage",
        "Magnificent Mansion",
        "Mirage Arcane",
        "Plane Shift",
        "Prismatic Spray",
        "Project Image",
        "Regenerate",
        "Resurrection",
        "Reverse Gravity",
        "Sequester",
        "Simulacrum",
        "Symbol",
        "Teleport"
    ],
    "8th Level": [
        "Animal Shapes",
        "Antimagic Field",
        "Antipathy/Sympathy",
        "Clone",
        "Control Weather",
        "Demiplane",
        "Dominate Monster",
        "Earthquake",
        "Feeblemind",
        "Glibness",
        "Holy Aura",
        "Incendiary Cloud",
        "Maze",
        "Mind Blank",
        "Power Word Stun",
        "Sunburst"
    ],
    "9th Level": [
        "Astral Projection",
        "Foresight",
        "Gate",
        "Imprisonment",
        "Mass Heal",
        "Meteor Swarm",
        "Power Word Kill",
        "Prismatic Wall",
        "Shapechange",
        "Storm of Vengeance",
        "Time Stop",
        "True Polymorph",
        "True Resurrection",
        "Weird",
        "Wish"
    ]
}

item_boons = [
    "Eternal Power: The item's magical properties no longer diminish over time, ensuring its lasting potency.",
    "Arcane Resonance: When attuned to this item, the user gains a +2 bonus to spell attack rolls and spell save DCs.",
    "Elemental Infusion: The item becomes infused with elemental power, allowing the user to choose one element (fire, ice, lightning, etc.) to enhance its effects.",
    "Warding Aura: The item emits a protective aura, providing resistance to a specific type of damage when wielded.",
    "Mana Infusion: The item gains the ability to absorb and store magical energy, granting the user a pool of extra spell slots.",
    "Mystic Bond: The user can attune to one additional magical item without penalty while attuned to this item.",
    "Dimensional Pouch: The item has a hidden pocket in a different dimension, allowing the user to retrieve small objects from it as a bonus action.",
    "Sorcerer's Insight: When holding the item, the user can cast the Identify spell at will without expending a spell slot.",
    "Celestial Harmony: The item resonates with celestial energy, granting resistance to radiant damage and the ability to cast Lesser Restoration once per day.",
    "Acolyte of Magic: The user gains proficiency in Arcana and advantage on saving throws against spells while attuned to the item.",
    "Empowered Strikes: Attacks made with this item deal an additional 1d6 damage of a type chosen by the user (fire, cold, lightning, etc.).",
    "Illusionary Shroud: The user can cast the Invisibility spell on themselves once per day while holding the item.",
    "Teleportation Charm: The item allows the user to cast the Misty Step spell once per day.",
    "Blink's Favor: The user can cast the Blink spell once per day while holding the item.",
    "Elemental Attunement: The user can change the elemental damage type of the item's attacks at will.",
    "Enchanted Smithing: The item can be used as a magical forge, allowing the user to craft minor magical items with it.",
    "Harmonious Presence: The item grants advantage on Charisma checks and advantage on saving throws against being frightened.",
    "Fey Bond: The user forms a bond with nature, gaining the ability to speak with animals and cast Speak with Plants once per day.",
    "Temporal Insight: The user gains the ability to cast the Haste spell once per day while holding the item.",
    "Sorcerous Mastery: The user can cast the Counterspell spell once per day without expending a spell slot while holding the item.",
    "Spell Echo: When casting a spell using this item, there's a 20% chance the spell is not expended and can be cast again.",
    "Fortified Defense: When attuned to this item, the user gains a +2 bonus to Armor Class.",
    "Evasive Maneuvers: While holding this item, the user can use a reaction to take no damage from an area effect spell they succeed on a saving throw against.",
    "Steadfast Resistance: The item grants resistance to a specific type of damage, chosen by the user, while wielded.",
    "Dimensional Step: Once per day, the user can cast the Dimension Door spell while holding the item.",
    "Planar Affinity: The item grants advantage on saving throws against spells and effects from other planes.",
    "Spectral Sight: While attuned to this item, the user can see invisible creatures and objects within 60 feet.",
    "Elemental Ward: The item absorbs the energy of a damaging spell once per day, converting it into temporary hit points for the user.",
    "Spell Siphon: Once per day, the user can absorb a spell targeted at them, storing its energy to be used later as a spell slot.",
    "Enchanted Scholar: The user gains proficiency in one additional skill of their choice while attuned to this item.",
    "Arcane Mark: The user can inscribe a unique arcane mark on objects or creatures, allowing them to track them through magical means.",
    "Eagle Eye: The item grants advantage on all ranged attack rolls while wielded.",
    "Shadowstep: Once per day, the user can cast the Shadow Step spell while holding the item.",
    "Deflection Ward: The item grants a +1 bonus to saving throws and can be used as an arcane focus for casting spells.",
    "Ethereal Grasp: While holding the item, the user can interact with and manipulate objects on the Ethereal Plane as if they were on the Material Plane.",
    "Charm Ward: The item grants advantage on saving throws against being charmed or magically controlled.",
    "Feywild Connection: Once per day, the user can cast the Misty Step spell and gain the ability to communicate with creatures of the Feywild while holding the item.",
    "Temporal Manipulation: The user gains the ability to cast the Slow spell once per day while holding the item.",
    "Rejuvenating Touch: The item allows the user to cast the Lesser Restoration spell once per day, healing various conditions.",
    "Champion's Resolve: Once per day, the user can automatically succeed on one failed saving throw while attuned to this item.",
    "Mana Leech: When the user lands a critical hit with a weapon enhanced by this item, they regain a spell slot of a level equal to half the damage dealt.",
    "Aegis Ward: The item grants resistance to all damage types while held, but this resistance can only be used once per day.",
    "Spellshaper's Insight: While attuned to this item, the user can spend 1 hour to change the damage type of one of their spells before casting it.",
    "Eldritch Absorption: The item can absorb a harmful spell once per day, storing its energy to empower the user's next spell with bonus damage.",
    "Blade Dancer: When the user wields a melee weapon enhanced by this item, they can make one additional attack as a bonus action during their turn.",
    "Sorcerer's Focus: While attuned to this item, the user can add their proficiency bonus to the damage of one spell of their choice each day.",
    "Phase Shift: Once per day, the user can cast the Blink spell while holding the item.",
    "Arcane Resonance: The item enhances the user's cantrips, allowing them to deal maximum damage with cantrip spells once per day.",
    "Ethereal Retaliation: When struck by a melee attack while holding the item, the user can use their reaction to deal force damage equal to their character level to the attacker.",
    "Dimensional Aegis: The item grants the user a +1 bonus to saving throws and can be used to cast the Shield spell once per day.",
    "Primal Surge: Once per day, the user can call upon the elemental forces, granting them resistance to a specific elemental damage type for an hour.",
    "Mystic Familiar: While attuned to this item, the user can summon a minor magical creature (familiar) to assist them for one hour each day.",
    "Searing Vengeance: When the user is reduced to 0 hit points, the item unleashes a fiery explosion, dealing fire damage to all nearby enemies.",
    "Vampiric Grasp: Successful attacks with a weapon enhanced by this item restore hit points to the user equal to half the damage dealt.",
    "Arcane Concealment: The item can cast the Invisibility spell on the user once per day, which lasts for up to an hour.",
    "Psychic Emanation: Once per day, the user can cast the Detect Thoughts spell while holding the item.",
    "Frostforged: The item grants the user resistance to cold damage and allows them to cast the Ray of Frost cantrip at will.",
    "Illusory Mirage: The item can cast the Mirror Image spell on the user once per day, creating illusory duplicates.",
    "Resonating Ward: The item grants advantage on saving throws against spells and abilities that target the user's Constitution.",
    "Chronomancer's Insight: Once per day, the user can cast the Haste spell on themselves while holding the item, gaining increased speed and additional actions for a minute.",
    "Celestial Beacon: When the user wields this item, it emits a soft, radiant light that dispels darkness in a 30-foot radius and can be used to cast the Light spell once per day.",
    "Elemental Infusion: This item can be attuned to a specific elemental affinity (fire, water, earth, or air). When attuned, it grants the user resistance to that element's damage type.",
    "Phantom Strike: Once per day, the user can make a melee attack that passes through solid objects, ignoring cover and gaining a +2 bonus to hit.",
    "Spectral Companion: While attuned to this item, the user can summon a spectral animal companion, such as a ghostly wolf or falcon, which can scout, attack, or aid them in various ways.",
    "Arcane Warding: The item provides a +1 bonus to AC and saving throws when the user is targeted by spells or magical effects.",
    "Empathic Resonance: When the user touches this item to a sentient creature, they can share emotions and thoughts, aiding in diplomatic negotiations or gaining insights into an enemy's motives.",
    "Thunderstrike: Once per day, the user can call down a bolt of lightning on a target, dealing lightning damage and potentially stunning the target.",
    "Time's Bane: This item grants the user a limited ability to manipulate time, allowing them to take an extra turn once per day.",
    "Chaos Echo: The item can cast the Mirror Image spell on the user once per day, creating multiple illusory duplicates that confuse attackers.",
    "Fey Charm: While attuned to this item, the user can communicate with and gain the cooperation of Fey creatures they encounter.",
    "Spellweaver's Attunement: The user can attune to an additional magical item while wielding this item.",
    "Blood Magic Reservoir: The item can absorb the user's blood to empower its abilities, providing additional uses or augmentations to its powers.",
    "Dimensional Pocket: Once per day, the user can access a small extradimensional space within the item, allowing them to retrieve stored objects or hide items from prying eyes.",
    "Astral Sight: The user gains the ability to see into the Astral Plane, revealing hidden portals, invisible creatures, and ethereal entities.",
    "Eldritch Ward: The item grants resistance to Eldritch damage and can cast Counterspell once per day.",
    "Harmonic Melody: When the user plays a musical instrument or sings while holding this item, they can cast spells without verbal components.",
    "Magnetic Grasp: The item allows the user to manipulate metal objects from a distance, effectively granting them telekinesis for metal objects within 30 feet.",
    "Blightborn: The user can channel the blight, causing plants to wither and die with a touch, or they can use it to enhance their spells related to decay.",
    "Soulbond Renewal: Once per day, the user can restore their hit points to their maximum value as long as they are holding this item.",
    "Nullifier's Touch: The item allows the user to nullify the magical properties of other magical items or suppress magical effects within a 10-foot radius.",
    "Phoenix's Resurgence: When the user is reduced to 0 hit points, this item immediately casts the *Revivify* spell on them without requiring components, bringing them back to life.",
    "Draconic Affinity: The user gains the ability to speak and understand Draconic, as well as a resistance to the damage type associated with the dragon color of their choice (e.g., fire for red dragons).",
    "Starshard Blade: This weapon can be commanded to shed radiant light, acting as a *Sunblade*, and emits a field of magical starlight that grants the user Darkvision within a 60-foot radius.",
    "Aegis of the Titans: Once per day, the user can summon a protective energy barrier that provides temporary hit points and advantage on saving throws for one minute.",
    "Divine Communion: The user can attune to this item during a long rest, granting them an additional spell slot of the highest level they can cast.",
    "Ethereal Grasp: This item allows the user to interact with objects and creatures on the Ethereal Plane as if they were on the Material Plane.",
    "Spirit Whisperer: When held, this item allows the user to communicate with and seek guidance from benevolent spirits, providing insights into current or upcoming challenges.",
    "Nature's Resilience: The user gains advantage on saving throws against natural hazards like storms, earthquakes, or wildfires, and they can cast *Speak with Plants* once per day.",
    "Stormforged: The item can call down the power of a storm, granting the user resistance to lightning and thunder damage and allowing them to cast *Call Lightning* once per day.",
    "Planar Harmony: Once per day, the user can meditate with this item, granting them the ability to plane shift to a specific plane of existence for one hour.",
    "Whispering Shadows: When worn as clothing, this item grants the user advantage on Dexterity (Stealth) checks and the ability to cast *Pass without Trace* once per day.",
    "Arcane Insight: The user gains proficiency in Arcana and has advantage on Intelligence (Arcana) checks. They can also cast *Identify* once per day.",
    "Elemental Channeler: The user can channel an elemental aspect, allowing them to change the damage type of spells they cast to a chosen elemental damage type (fire, cold, lightning, or acid) once per day.",
    "Planar Repulsion: This item provides the user with resistance to force damage and the ability to cast *Mage Armor* once per day without using a spell slot.",
    "Hallowed Ground: When planted in the earth, this item creates a 30-foot-radius area of magical consecration, providing protection against undead and fiends and granting advantage on Turn Undead attempts.",
    "Resonant Echo: The user gains proficiency in Performance (Percussion) and can cast *Thunderwave* once per day, affecting a 15-foot radius.",
    "Moonlit Path: While attuned to this item, the user can follow moonlight to find safe paths through treacherous terrain, granting advantage on Survival checks to navigate in the wild.",
    "Temporal Anchor: The user can spend a bonus action to freeze or unfreeze a small object in time, allowing them to carry or manipulate it without interference from the flow of time.",
    "Illusionist's Veil: The user gains proficiency in Deception and can cast *Disguise Self* once per day without expending a spell slot.",
    "Beastmaster's Bond: The user can form a telepathic bond with a beast of CR 1 or lower, allowing them to communicate and share senses with the creature within a mile."
]

item_curses = [
    "Dampening Curse: The item's magical properties become unreliable. It functions as a non-magical item 50% of the time.",
    "Siphoning Curse: The item drains the user's life force. Whenever it is used, the user loses 1 hit point.",
    "Fragmented Curse: The item is shattered into multiple pieces, each holding a fraction of its power. It requires reassembly before it can be used.",
    "Curse of Confusion: The user often confuses the item's effects. When activated, there's a 50% chance it will target a random creature or area instead.",
    "Haunting Curse: The item is inhabited by a vengeful spirit. At night, it emits eerie noises and dim lights, making stealth impossible.",
    "Cursed Bond: The item becomes inseparable from the user. They cannot willingly part with it, even if it would be strategically advantageous.",
    "Greed's Curse: The item compels the user to hoard treasure. They must succeed on a Wisdom saving throw or be unable to part with valuable items.",
    "Rust Curse: The item slowly corrodes and rusts, losing its magical properties over time.",
    "Fragility Curse: The item becomes fragile and easily damaged. It gains the Fragile property, and if it breaks, it can't be repaired.",
    "Inversion Curse: The item's magical effects work in reverse, often causing harm instead of help.",
    "Curse of Vulnerability: The item's bearer becomes more susceptible to a specific damage type while wielding it.",
    "Time-locked Curse: The item is bound in time, only functioning during specific hours of the day or phases of the moon.",
    "Curse of Avarice: The user becomes obsessively possessive of the item, refusing to share or use it for any purpose other than personal gain.",
    "Cursed Aegis: The item offers no protection against a specific type of attack or effect.",
    "Disorientation Curse: The user frequently loses their sense of direction while carrying the item.",
    "Undying Curse: The item cannot be destroyed or discarded, returning to the user if lost or abandoned.",
    "Chaos Aura: The item emits a chaotic aura that causes random magical surges in the vicinity.",
    "Sacrificial Curse: The item demands the user to offer sacrifices or perform malevolent acts to activate its powers.",
    "Shadow Infestation: The item attracts shadowy entities that occasionally attack the user.",
    "Void Bond: The item forms a psychic bond with the user, causing vivid, unsettling nightmares and visions.",
    "Corrosive Curse: The item corrodes over time, contaminating any container it's stored in. It has a chance to destroy non-magical items in its vicinity.",
    "Curse of the False Wielder: The item refuses to function for anyone except the person who initially cursed it.",
    "Amplification Curse: The item's magical effects are amplified, but at a cost. When used, there's a chance of wild, uncontrollable magic surges.",
    "Soulbind Curse: The item binds to the user's soul, making it painful to part with. They take psychic damage if they attempt to willingly abandon it.",
    "Sacrificial Taint: To activate the item's powers, it requires the user to make a blood sacrifice.",
    "Lingering Agony: The item causes a dull, constant pain to the user, imposing disadvantage on concentration checks.",
    "Curse of Temptation: The item appears irresistible to thieves and malevolent beings, making it more likely to be stolen.",
    "Cursed Echo: Whenever the item is used, it leaves behind an eerie echo that can be heard by anyone nearby, revealing the user's location.",
    "Fragmented Memory: The item holds memories of its previous owners, sometimes causing the user to experience their past traumas and emotions.",
    "Curse of the Ephemeral: The item has a limited number of uses before it dissipates into mist, rendering it useless.",
    "Compulsive Liar's Curse: The user becomes afflicted with a compulsion to lie excessively while using the item.",
    "Curse of Ego: The item's sentience grows, and it attempts to manipulate or control the user for its own purposes.",
    "Fractured Reality: The item warps reality slightly around it, causing minor distortions in perception for those nearby.",
    "Cursed Familiar: The item attracts the attention of malevolent creatures who perceive it as a threat.",
    "Mimicry Curse: The item occasionally transforms into an identical mundane object, causing confusion for the user.",
    "Curse of Regression: The item regresses in power with each use, requiring a lengthy ritual to restore its abilities.",
    "Hungering Curse: The item craves the user's life force, draining hit points each time it's activated.",
    "Temporal Drift: The item has a tendency to temporarily displace the user in time, causing them to experience time-related anomalies.",
    "Curse of Visions: The item grants occasional prophetic visions, but they are often cryptic and maddening.",
    "Theft Attractor: The item attracts thieves and ne'er-do-wells, who are compelled to steal it from the user.",
    "Curse of the Bound Spirit: The item is inhabited by a trapped spirit that occasionally takes control, causing the user to act against their will.",
    "Bleeding Curse: The item continually drips blood, making stealth nearly impossible and causing all living creatures to become hostile.",
    "Curse of Vulnerability: While attuned to the item, the user is vulnerable to a specific type of damage, such as fire, cold, or lightning.",
    "Necrotic Infusion: The item infuses the user with necrotic energy, causing their appearance to wither and decay over time.",
    "Curse of Blinding: Using the item occasionally blinds the user temporarily, rendering them effectively blind for a period.",
    "Betrayer's Bond: The item compels the user to betray their allies when it offers a tactical advantage.",
    "Curse of Enfeeblement: The item saps the user's strength, imposing disadvantage on all Strength checks and saving throws.",
    "Haunted Presence: The item attracts malevolent spirits, causing eerie occurrences and supernatural phenomena around the user.",
    "Curse of Nightmares: The user is plagued by vivid and terrifying nightmares, suffering from insomnia and exhaustion.",
    "Dissonant Resonance: The item emits a dissonant sound that alerts enemies to the user's presence when activated.",
    "Curse of Fragmentation: The item is broken into multiple pieces, each of which has a mind of its own and may act independently.",
    "Spectral Attachment: The item occasionally phases out of existence, becoming ethereal and unusable.",
    "Curse of Sloth: The user becomes lethargic and slow while attuned to the item, suffering a penalty to their movement speed.",
    "Doppelganger's Curse: The item creates an illusory duplicate of the user, making them a target for confusion and deception.",
    "Curse of Uncontrollable Magic: The item causes wild surges of magic during spellcasting, leading to unpredictable results.",
    "Feybond Curse: The item attracts the attention of mischievous fey creatures who may interfere with the user's actions.",
    "Curse of Draining Echoes: The item drains the user's memories and experiences, causing temporary amnesia.",
    "Elemental Imbalance: The item upsets the user's elemental balance, making them vulnerable to a specific elemental damage type.",
    "Curse of Hunger: The item craves a specific substance, such as precious metals or gems, and must be fed regularly.",
    "Psychic Intrusion: The item occasionally allows psychic intrusions, making the user susceptible to mind-reading and mental manipulation.",
    "Curse of Lethal Feedback: Whenever the item is activated, there's a chance it backfires, dealing damage or an adverse effect to the user.",
    "Infernal Bond: The item connects the user to infernal forces, attracting attention from devils and demons.",
    "Curse of Clinginess: The item becomes nearly impossible to let go of once attuned, causing the user to struggle to drop or switch to other equipment.",
    "Spectral Shackles: The user is bound to spectral chains, reducing their movement speed and making them easier to grapple.",
    "Curse of Fragmented Mind: The item fragments the user's thoughts, causing them to occasionally lose focus and take penalties to Intelligence-related tasks.",
    "Malevolent Whispers: The item whispers malevolent suggestions to the user, leading to irrational or harmful decisions.",
    "Curse of Entropy: The item speeds up the natural aging process of the user, causing physical and mental deterioration.",
    "Elemental Attraction: The item attracts elemental creatures, leading to unexpected elemental encounters.",
    "Curse of Shattered Reflections: The user's reflection becomes fractured and distorted, making them difficult to recognize and leading to social disadvantages.",
    "Hexed Vision: The item occasionally hexes the user's vision, causing them to see illusions or enemies that aren't there.",
    "Curse of Compulsive Use: The user becomes compelled to use the item, even when it's not strategically wise or safe to do so.",
    "Void Resonance: The item resonates with void energy, causing periodic disruptions to magic and spellcasting.",
    "Curse of Lost Time: The user experiences bouts of lost time while attuned to the item, unaware of what they did during those periods.",
    "Phantom Menace: The item creates illusory threats, causing the user to become paranoid and act defensively.",
    "Curse of Weakened Resolve: The item weakens the user's resolve, causing them to struggle with moral and ethical decisions.",
    "Magnet for Darkness: The item attracts creatures of darkness, leading to encounters with vampires, shadow creatures, and other sinister beings.",
    "Curse of the Echoing Voice: The user's voice echoes unnaturally, making stealth and subtlety nearly impossible.",
    "Fey Distortion: The item distorts the user's presence in the Feywild, leading to strange interactions and unpredictable Fey encounters.",
    "Curse of Disjointed Senses: The user's senses become disjointed, leading to unpredictable sensations and sensory hallucinations.",
    "Sentience Agitation: The item's sentience becomes agitated, occasionally taking control and acting independently of the user's wishes.",
    "Curse of Fiery Repercussion: When the item is used, it has a chance of igniting the user, causing them to take fire damage.",
    "Astral Instability: The item causes the user to occasionally phase into the Astral Plane, making them intangible and vulnerable.",
    "Curse of Betrayal: The item compels the user to betray allies or make treacherous decisions at inopportune times.",
    "Toxic Aura: The item emits a toxic aura, poisoning the user and those nearby over time.",
    "Curse of Mute Misery: The user loses the ability to speak or communicate while attuned to the item.",
    "Disorienting Glare: The item emits a blinding glare when activated, affecting the user and allies within range.",
    "Curse of Frailty: The item weakens the user's body, causing them to take penalties to Strength-related tasks.",
    "Magnetic Disturbance: The item disrupts magnetic fields, causing compasses and navigation tools to malfunction in its presence.",
    "Curse of False Riches: The user becomes obsessed with the appearance of wealth, making them squander actual riches and acquire fake treasures.",
    "Spectral Bonds: The item binds the user to malevolent spirits, causing them to be haunted and tormented.",
    "Curse of Amnesia: The user occasionally forgets their own identity and past while attuned to the item.",
    "Soul Fragmentation: The item fragments the user's soul, making them vulnerable to soul-stealing magic.",
    "Curse of Unquenchable Thirst: The user is cursed with an insatiable thirst for liquids, making them consume valuable resources.",
    "Mind Twister: The item twists the user's thoughts, leading to irrational or chaotic behavior.",
    "Curse of the Decayed Mind: The user's mental faculties decay over time, causing penalties to Intelligence-related tasks.",
    "Elemental Discord: The item causes erratic elemental surges, leading to unpredictable elemental effects.",
    "Curse of the Shifting Gaze: The user's eyes shift uncontrollably, making them difficult to trust or read.",
    "Hexed Fate: The item hexes the user's fate, leading to unpredictably good or bad luck, often at the worst moments.",
    "Curse of Forsaken Allies: The item compels the user to abandon allies in moments of need.",
    "Eldritch Contagion: The item is tainted with an eldritch contagion that spreads to anyone who touches it."
]
